services:
  - type: web
    name: marketpulse
    runtime: docker
    plan: free
    envVars:
      - key: DB_NAME
        value: neondb
      - key: DB_USER
        value: neondb_owner
      - key: DB_PASSWORD
        value: npg_ZPXJS7Y6CBsf
      - key: DB_HOST
        value: ep-hidden-dawn-aqv55xjw-pooler.c-8.us-east-1.aws.neon.tech
      - key: DB_PORT
        value: "5432"